(cl:in-package sick_lidar_localization-msg)
(cl:export '(ERRORCODE-VAL
          ERRORCODE
          SCANCOUNTER-VAL
          SCANCOUNTER
          TIMESTAMP-VAL
          TIMESTAMP
          POSEX-VAL
          POSEX
          POSEY-VAL
          POSEY
          POSEYAW-VAL
          POSEYAW
          RESERVED1-VAL
          RESERVED1
          RESERVED2-VAL
          RESERVED2
          QUALITY-VAL
          QUALITY
          OUTLIERSRATIO-VAL
          OUTLIERSRATIO
          COVARIANCEX-VAL
          COVARIANCEX
          COVARIANCEY-VAL
          COVARIANCEY
          COVARIANCEYAW-VAL
          COVARIANCEYAW
          RESERVED3-VAL
          RESERVED3
))