(cl:defpackage sick_lidar_localization-msg
  (:use )
  (:export
   "<SICKLOCCOLATELEGRAMMSG>"
   "SICKLOCCOLATELEGRAMMSG"
   "<SICKLOCDIAGNOSTICMSG>"
   "SICKLOCDIAGNOSTICMSG"
   "<SICKLOCRESULTPORTCRCMSG>"
   "SICKLOCRESULTPORTCRCMSG"
   "<SICKLOCRESULTPORTHEADERMSG>"
   "SICKLOCRESULTPORTHEADERMSG"
   "<SICKLOCRESULTPORTPAYLOADMSG>"
   "SICKLOCRESULTPORTPAYLOADMSG"
   "<SICKLOCRESULTPORTTELEGRAMMSG>"
   "SICKLOCRESULTPORTTELEGRAMMSG"
   "<SICKLOCRESULTPORTTESTCASEMSG>"
   "SICKLOCRESULTPORTTESTCASEMSG"
  ))

