// Generated by gencpp from file sick_lidar_localization/SickLocResultPortCrcMsg.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCRESULTPORTCRCMSG_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCRESULTPORTCRCMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sick_lidar_localization
{
template <class ContainerAllocator>
struct SickLocResultPortCrcMsg_
{
  typedef SickLocResultPortCrcMsg_<ContainerAllocator> Type;

  SickLocResultPortCrcMsg_()
    : Checksum(0)  {
    }
  SickLocResultPortCrcMsg_(const ContainerAllocator& _alloc)
    : Checksum(0)  {
  (void)_alloc;
    }



   typedef uint16_t _Checksum_type;
  _Checksum_type Checksum;





  typedef boost::shared_ptr< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SickLocResultPortCrcMsg_

typedef ::sick_lidar_localization::SickLocResultPortCrcMsg_<std::allocator<void> > SickLocResultPortCrcMsg;

typedef boost::shared_ptr< ::sick_lidar_localization::SickLocResultPortCrcMsg > SickLocResultPortCrcMsgPtr;
typedef boost::shared_ptr< ::sick_lidar_localization::SickLocResultPortCrcMsg const> SickLocResultPortCrcMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator1> & lhs, const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator2> & rhs)
{
  return lhs.Checksum == rhs.Checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator1> & lhs, const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sick_lidar_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df59506c295b6d20407c4cced0a0b9aa";
  }

  static const char* value(const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf59506c295b6d20ULL;
  static const uint64_t static_value2 = 0x407c4cced0a0b9aaULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_lidar_localization/SickLocResultPortCrcMsg";
  }

  static const char* value(const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Definition of ros message SickLocResultPortCrcMsg.\n"
"# SickLocResultPortCrcMsg publishes the CRC trailer of a result port telegram\n"
"# for sick localization (2 byte). \n"
"# Checksum details:\n"
"# * Width: 16 bits\n"
"# * Truncated polynomial: 0x1021 CRC polynomials with orders of x16 + x12 + x5 + 1 (counted without the leading '1' bit)\n"
"# * Initial value = 0xFFFF\n"
"# See chapter 5.9 (\"About result port telegrams\") of the operation manual for further details.\n"
"\n"
"uint16 Checksum # CRC16-CCITT over length of header (52 bytes) and payload (52 bytes) without 2 bytes of this trailer. Size: UInt16 = 2 byte\n"
"\n"
;
  }

  static const char* value(const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SickLocResultPortCrcMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_lidar_localization::SickLocResultPortCrcMsg_<ContainerAllocator>& v)
  {
    s << indent << "Checksum: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCRESULTPORTCRCMSG_H
