// Generated by gencpp from file sick_lidar_localization/SickLocRequestResultDataSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCREQUESTRESULTDATASRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCREQUESTRESULTDATASRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocRequestResultDataSrvRequest.h>
#include <sick_lidar_localization/SickLocRequestResultDataSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocRequestResultDataSrv
{

typedef SickLocRequestResultDataSrvRequest Request;
typedef SickLocRequestResultDataSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocRequestResultDataSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_lidar_localization::SickLocRequestResultDataSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocRequestResultDataSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocRequestResultDataSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocRequestResultDataSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestResultDataSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocRequestResultDataSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocRequestResultDataSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocRequestResultDataSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocRequestResultDataSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestResultDataSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocRequestResultDataSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestResultDataSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocRequestResultDataSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocRequestResultDataSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocRequestResultDataSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocRequestResultDataSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestResultDataSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCREQUESTRESULTDATASRV_H
