// Generated by gencpp from file sick_lidar_localization/SickLocSetPoseSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETPOSESRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETPOSESRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocSetPoseSrvRequest.h>
#include <sick_lidar_localization/SickLocSetPoseSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocSetPoseSrv
{

typedef SickLocSetPoseSrvRequest Request;
typedef SickLocSetPoseSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetPoseSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrv > {
  static const char* value()
  {
    return "11bcade26cc02b7bbcb448a2abedd38e";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetPoseSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocSetPoseSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocSetPoseSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetPoseSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetPoseSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetPoseSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetPoseSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetPoseSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetPoseSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetPoseSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetPoseSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetPoseSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetPoseSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetPoseSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetPoseSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETPOSESRV_H
