// Generated by gencpp from file sick_lidar_localization/SickLocIsSystemReadySrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCISSYSTEMREADYSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCISSYSTEMREADYSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocIsSystemReadySrvRequest.h>
#include <sick_lidar_localization/SickLocIsSystemReadySrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocIsSystemReadySrv
{

typedef SickLocIsSystemReadySrvRequest Request;
typedef SickLocIsSystemReadySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocIsSystemReadySrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_lidar_localization::SickLocIsSystemReadySrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocIsSystemReadySrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocIsSystemReadySrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocIsSystemReadySrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocIsSystemReadySrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocIsSystemReadySrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocIsSystemReadySrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocIsSystemReadySrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocIsSystemReadySrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocIsSystemReadySrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocIsSystemReadySrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocIsSystemReadySrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocIsSystemReadySrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocIsSystemReadySrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocIsSystemReadySrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocIsSystemReadySrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocIsSystemReadySrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCISSYSTEMREADYSRV_H
