// Generated by gencpp from file sick_lidar_localization/SickLocSetResultModeSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTMODESRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTMODESRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocSetResultModeSrvRequest.h>
#include <sick_lidar_localization/SickLocSetResultModeSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocSetResultModeSrv
{

typedef SickLocSetResultModeSrvRequest Request;
typedef SickLocSetResultModeSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetResultModeSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrv > {
  static const char* value()
  {
    return "46e3fbb42467cdb3ed60e9a1d6e7dbc3";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetResultModeSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultModeSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocSetResultModeSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetResultModeSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultModeSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultModeSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultModeSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultModeSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetResultModeSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultModeSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetResultModeSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultModeSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultModeSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultModeSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultModeSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetResultModeSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultModeSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTMODESRV_H
