// Generated by gencpp from file sick_lidar_localization/SickLocStartLocalizingSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTARTLOCALIZINGSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTARTLOCALIZINGSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocStartLocalizingSrvRequest.h>
#include <sick_lidar_localization/SickLocStartLocalizingSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocStartLocalizingSrv
{

typedef SickLocStartLocalizingSrvRequest Request;
typedef SickLocStartLocalizingSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocStartLocalizingSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocStartLocalizingSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocStartLocalizingSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocStartLocalizingSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocStartLocalizingSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocStartLocalizingSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocStartLocalizingSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTARTLOCALIZINGSRV_H
