// Generated by gencpp from file sick_lidar_localization/SickLocRequestTimestampSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCREQUESTTIMESTAMPSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCREQUESTTIMESTAMPSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocRequestTimestampSrvRequest.h>
#include <sick_lidar_localization/SickLocRequestTimestampSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocRequestTimestampSrv
{

typedef SickLocRequestTimestampSrvRequest Request;
typedef SickLocRequestTimestampSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocRequestTimestampSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrv > {
  static const char* value()
  {
    return "ae8b1571bf8be63e0bdad9873d14be2b";
  }

  static const char* value(const ::sick_lidar_localization::SickLocRequestTimestampSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocRequestTimestampSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocRequestTimestampSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocRequestTimestampSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestTimestampSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocRequestTimestampSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocRequestTimestampSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocRequestTimestampSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocRequestTimestampSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestTimestampSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocRequestTimestampSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestTimestampSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocRequestTimestampSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocRequestTimestampSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocRequestTimestampSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocRequestTimestampSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocRequestTimestampSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCREQUESTTIMESTAMPSRV_H
