// Generated by gencpp from file sick_lidar_localization/SickLocSetResultPortSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTPORTSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTPORTSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocSetResultPortSrvRequest.h>
#include <sick_lidar_localization/SickLocSetResultPortSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocSetResultPortSrv
{

typedef SickLocSetResultPortSrvRequest Request;
typedef SickLocSetResultPortSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetResultPortSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrv > {
  static const char* value()
  {
    return "22d338505934787b6445bcb45da196e0";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetResultPortSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultPortSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocSetResultPortSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetResultPortSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultPortSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultPortSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultPortSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultPortSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultPortSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultPortSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultPortSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultPortSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultPortSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultPortSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTPORTSRV_H
