// Generated by gencpp from file sick_lidar_localization/SickLocStopSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTOPSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTOPSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocStopSrvRequest.h>
#include <sick_lidar_localization/SickLocStopSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocStopSrv
{

typedef SickLocStopSrvRequest Request;
typedef SickLocStopSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocStopSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStopSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStopSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocStopSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocStopSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStopSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStopSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStopSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStopSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocStopSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStopSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocStopSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocStopSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocStopSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocStopSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStopSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStopSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStopSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStopSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocStopSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStopSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocStopSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocStopSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocStopSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocStopSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStopSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTOPSRV_H
