// Generated by gencpp from file sick_lidar_localization/SickLocColaTelegramSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCCOLATELEGRAMSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCCOLATELEGRAMSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocColaTelegramSrvRequest.h>
#include <sick_lidar_localization/SickLocColaTelegramSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocColaTelegramSrv
{

typedef SickLocColaTelegramSrvRequest Request;
typedef SickLocColaTelegramSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocColaTelegramSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrv > {
  static const char* value()
  {
    return "60dfc3041906873e51cdec40ce270a34";
  }

  static const char* value(const ::sick_lidar_localization::SickLocColaTelegramSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocColaTelegramSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocColaTelegramSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocColaTelegramSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocColaTelegramSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocColaTelegramSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocColaTelegramSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocColaTelegramSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocColaTelegramSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocColaTelegramSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocColaTelegramSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocColaTelegramSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocColaTelegramSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocColaTelegramSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocColaTelegramSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocColaTelegramSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocColaTelegramSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCCOLATELEGRAMSRV_H
