// Generated by gencpp from file sick_lidar_localization/SickLocSetResultEndiannessSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTENDIANNESSSRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTENDIANNESSSRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocSetResultEndiannessSrvRequest.h>
#include <sick_lidar_localization/SickLocSetResultEndiannessSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocSetResultEndiannessSrv
{

typedef SickLocSetResultEndiannessSrvRequest Request;
typedef SickLocSetResultEndiannessSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetResultEndiannessSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrv > {
  static const char* value()
  {
    return "ad546145ccc5332dee356f4fbbf0ae49";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetResultEndiannessSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocSetResultEndiannessSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocSetResultEndiannessSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultEndiannessSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultEndiannessSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultEndiannessSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocSetResultEndiannessSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocSetResultEndiannessSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSETRESULTENDIANNESSSRV_H
