// Generated by gencpp from file sick_lidar_localization/SickLocStateSrv.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTATESRV_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTATESRV_H

#include <ros/service_traits.h>


#include <sick_lidar_localization/SickLocStateSrvRequest.h>
#include <sick_lidar_localization/SickLocStateSrvResponse.h>


namespace sick_lidar_localization
{

struct SickLocStateSrv
{

typedef SickLocStateSrvRequest Request;
typedef SickLocStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocStateSrv
} // namespace sick_lidar_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStateSrv > {
  static const char* value()
  {
    return "112e7992c0a1025af8b2c1b11d515e09";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStateSrv&) { return value(); }
};

template<>
struct DataType< ::sick_lidar_localization::SickLocStateSrv > {
  static const char* value()
  {
    return "sick_lidar_localization/SickLocStateSrv";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStateSrvRequest> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStateSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocStateSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocStateSrvRequest> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocStateSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocStateSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStateSrvResponse> should match
// service_traits::MD5Sum< ::sick_lidar_localization::SickLocStateSrv >
template<>
struct MD5Sum< ::sick_lidar_localization::SickLocStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_lidar_localization::SickLocStateSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_lidar_localization::SickLocStateSrvResponse> should match
// service_traits::DataType< ::sick_lidar_localization::SickLocStateSrv >
template<>
struct DataType< ::sick_lidar_localization::SickLocStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_lidar_localization::SickLocStateSrv >::value();
  }
  static const char* value(const ::sick_lidar_localization::SickLocStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTATESRV_H
