// Generated by gencpp from file sick_lidar_localization/SickLocStartLocalizingSrvRequest.msg
// DO NOT EDIT!


#ifndef SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTARTLOCALIZINGSRVREQUEST_H
#define SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTARTLOCALIZINGSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sick_lidar_localization
{
template <class ContainerAllocator>
struct SickLocStartLocalizingSrvRequest_
{
  typedef SickLocStartLocalizingSrvRequest_<ContainerAllocator> Type;

  SickLocStartLocalizingSrvRequest_()
    {
    }
  SickLocStartLocalizingSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SickLocStartLocalizingSrvRequest_

typedef ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<std::allocator<void> > SickLocStartLocalizingSrvRequest;

typedef boost::shared_ptr< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest > SickLocStartLocalizingSrvRequestPtr;
typedef boost::shared_ptr< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest const> SickLocStartLocalizingSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sick_lidar_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_lidar_localization/SickLocStartLocalizingSrvRequest";
  }

  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Definition of ROS service SickLocStartLocalizing for sick localization.\n"
"#\n"
"# ROS service SickLocStartLocalizing starts localization\n"
"# by sending cola command (\"sMN LocStartLocalizing\").\n"
"#\n"
"# See Telegram-Listing-v1.1.0.241R.pdf for further details about \n"
"# Cola telegrams and this command.\n"
"\n"
"#\n"
"# Request (input)\n"
"#\n"
"\n"
;
  }

  static const char* value(const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SickLocStartLocalizingSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sick_lidar_localization::SickLocStartLocalizingSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SICK_LIDAR_LOCALIZATION_MESSAGE_SICKLOCSTARTLOCALIZINGSRVREQUEST_H
