# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from r2serial_driver/Num.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Num(genpy.Message):
  _md5sum = "137910bf2ef85fa95265084c3edcdb56"
  _type = "r2serial_driver/Num"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 RMID
uint8 TMID 
uint8 ID
uint8 PID
uint8 DataNum
uint8 Dta_Low
uint8 Dta_High
uint8 Sum


"""
  __slots__ = ['RMID','TMID','ID','PID','DataNum','Dta_Low','Dta_High','Sum']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       RMID,TMID,ID,PID,DataNum,Dta_Low,Dta_High,Sum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Num, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.RMID is None:
        self.RMID = 0
      if self.TMID is None:
        self.TMID = 0
      if self.ID is None:
        self.ID = 0
      if self.PID is None:
        self.PID = 0
      if self.DataNum is None:
        self.DataNum = 0
      if self.Dta_Low is None:
        self.Dta_Low = 0
      if self.Dta_High is None:
        self.Dta_High = 0
      if self.Sum is None:
        self.Sum = 0
    else:
      self.RMID = 0
      self.TMID = 0
      self.ID = 0
      self.PID = 0
      self.DataNum = 0
      self.Dta_Low = 0
      self.Dta_High = 0
      self.Sum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.RMID, _x.TMID, _x.ID, _x.PID, _x.DataNum, _x.Dta_Low, _x.Dta_High, _x.Sum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.RMID, _x.TMID, _x.ID, _x.PID, _x.DataNum, _x.Dta_Low, _x.Dta_High, _x.Sum,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.RMID, _x.TMID, _x.ID, _x.PID, _x.DataNum, _x.Dta_Low, _x.Dta_High, _x.Sum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.RMID, _x.TMID, _x.ID, _x.PID, _x.DataNum, _x.Dta_Low, _x.Dta_High, _x.Sum,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
