(cl:in-package sick_lidar_localization-srv)
(cl:export '(COLA_ASCII_REQUEST-VAL
          COLA_ASCII_REQUEST
          WAIT_RESPONSE_TIMEOUT-VAL
          WAIT_RESPONSE_TIMEOUT
          COLA_ASCII_RESPONSE-VAL
          COLA_ASCII_RESPONSE
          SEND_TIMESTAMP_SEC-VAL
          SEND_TIMESTAMP_SEC
          SEND_TIMESTAMP_NSEC-VAL
          SEND_TIMESTAMP_NSEC
          RECEIVE_TIMESTAMP_SEC-VAL
          RECEIVE_TIMESTAMP_SEC
          RECEIVE_TIMESTAMP_NSEC-VAL
          RECEIVE_TIMESTAMP_NSEC
))